### ISSUE TITLE
States/Scenes

### ISSUE THREAD

**Issue by ayebear** [ayebear/oregon-trail#1]
A state is an actual class definition, a scene is simply a specific instance of a state.

We need the following scenes:
- [x] Choose job (banker, farmer, etc.) - menu state
- [x] Create party UI - multiple input state
- [x] Store UI - store state
- [x] Yes/no - based on menu state
- [ ] Crossing river animation
- [ ] Main menu option states:
  - [x] Continue on trail
  - [x] Check supplies (global)
  - [ ] Look at map (global)
  - [x] Change pace
  - [x] Change food rations
  - [x] Stop to rest
  - [x] Attempt to trade
  - [x] Talk to people
  - [x] Buy supplies

**Comment by Derar1** [comment]
Thieves state
Weather state
wagon breaking down state (being able to fix it or not) 
catching fish 
random flooding at river crossings with random flood height and the 3 options to cross it
